### PR TITLE
Assorted fixes for migrations

### LINKED ISSUE #111: Migrations are not run correctly
I have created a big migration, but found out that it was run **partially** or incorrectly. 
I don't know the real reason for this since this happened in production (and destroyed some of the users' data).

When the migration "finished" and the app loaded, queries were failing with errors referencing temporary tables that were in the process of recreation due to the migration. For example, the migration had `Entry_old` and `Entry_new`, at the end dropping the old and renaming the new. 

The migration was not correct on my side - some issues left. But the result of that was NOT what I expected. instead of failing and rolling back - the migration destroyed part of the data / ran halfway / left the database in an inconsistent state / raced. As a result, the database was fucked up in an unknown intermediate state. 

Writing a new migration that fixed the previous one didn't help.

This is my setup:
```kotlin
AndroidxSqliteDriver(
    createConnection = { driver.open(it, flags) },
    databaseType = AndroidxSqliteDatabaseType.FileProvider { fileProvider(BuildFlags.DatabaseName) },
    configuration = AndroidxSqliteConfiguration(
        isForeignKeyConstraintsEnabled = true,
        journalMode = SqliteJournalMode.WAL,
    ),
    schema = AppDatabase.Schema,
)
```

I suspect one or more are happening:

1. Migrations are not run with disabled constraints. Migrations must never run with constraints, especially undeferred ones, otherwise during table recreation, their actions `CASCADE` / `SET NULL` will be run. My data loss suggests this possibly happened.
2. Migrations are not run on a single thread, before ANY other access to the database is allowed. The migrations must be the first and the only thing to run. The app accessing data from other threads can ruin the data consistency.
3. Migrations are not run within a single, atomic transaction. If one operation within a migration fails, the migration should be rolled back **completely**. My issues with tables deleted at the end of migrations still being referenced in queries as the migration finished, suggest this may have happened.
4. Migrations swallow errors. Any problem during a migration must result in it being not run/rolled back. The fact that the app booted and was partially working in a broken state suggests the migrations do not handle errors correctly. 

Can you please investigate? I need to restore users' data and it would be great if we shipped the proper fix to prevent me from completely annihilating users databases.

### PR DESCRIPTION
**Pull request by eygraber**
Fixes #111

### CODE REVIEW

File: library/src/commonMain/kotlin/com/eygraber/sqldelight/androidx/driver/AndroidxSqliteDriver.kt [hunk 1]
```diff
@@ -426,6 +456,52 @@ public class AndroidxSqliteDriver(
...
+    if(configuration.isForeignKeyConstraintsCheckedAfterCreateOrUpdate) {
+      prepare("PRAGMA foreign_key_check;").use { check ->
+        val violations = mutableListOf<String>()
+        while(check.step()) {
+          val referencingTable = check.getText(0)
+          val referencingRowId = check.getInt(1)
+          val referencedTable = check.getText(2)
+          val referencingConstraintIndex = check.getInt(3)
+
+          violations.add(
```
Comment (Nek-12) [inline library/src/commonMain/kotlin/com/eygraber/sqldelight/androidx/driver/AndroidxSqliteDriver.kt:481]: This seems to be creating one such strong for each row. For a large database, this can be hundreds of thousands of rows. We should limit the amount of items this will return

Comment (eygraber) [reply library/src/commonMain/kotlin/com/eygraber/sqldelight/androidx/driver/AndroidxSqliteDriver.kt:481]: It should be every row that has a constraint violation, which could be helpful in some scenarios, but I could add a flag to limit how much is returned.

Comment (Nek-12) [reply library/src/commonMain/kotlin/com/eygraber/sqldelight/androidx/driver/AndroidxSqliteDriver.kt:481]: Yes, I was saying:  A wrong migration will for example break all constraints in a table. That number is 50+k for many of my customers.  I dont need to know r very single one to understand something is wrong. I suggest just simply limiting it to ~100 rows + total count at most.

Comment (eygraber) [reply library/src/commonMain/kotlin/com/eygraber/sqldelight/androidx/driver/AndroidxSqliteDriver.kt:481]: True, but I don't want to be in a scenario where someone needed the 101st row to find the problem. I'll update it to not pass all of them to the exception's message, expose the violations as a property, and add a flag to limit how many results are read.

Comment (eygraber) [reply library/src/commonMain/kotlin/com/eygraber/sqldelight/androidx/driver/AndroidxSqliteDriver.kt:481]: I thought about it more and went with a default of 100 - https://github.com/eygraber/sqldelight-androidx-driver/pull/113
